apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: lili2024-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: default-route-openshift-image-registry.apps.sandbox-m2.ll9k.p1.openshiftapps.com/lili2024-dev/frontend:latest
        ports:
        - containerPort: 3000 # Updated to match the app's internal port
        env:
          - name: PORT
            value: "3000"  # Updated to match the internal app port

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: lili2024-dev
spec:
  selector:
    app: frontend
  ports:
  - name: http
    protocol: TCP
    port: 8080         # Service port exposed for external access
    targetPort: 3000   # Updated to match the internal port of the application
