apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: default-route-openshift-image-registry.apps.sandbox-m2.ll9k.p1.openshiftapps.com/lili2024-dev/payment-service:latest
        ports:
        - containerPort: 8083

---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8083
  type: ClusterIP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: payment-service-route
spec:
  to:
    kind: Service
    name: payment-service
  port:
    targetPort: 8083

